baseURL = "http://pawsys.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
author = "Pawel Sysiak"
# description = "Pawel Sysiak blog"

[taxonomies]
  collection = "collections"
# old
  link = "links"
  impact = "impacts"
  craft = "crafts"
  img = "images"
  priority = "priorities"
  author = "authors"
  title = "title"
  subtitle = "subtitles"
  type = "types"

# My stuff
enableEmoji = "true"
paginate = "4"
